# This is the config file for BasicQuests.
# This config was generated for version 0.6

# You can delete this file to regenerate the default config on server reload.



# GENERAL

# amount of quests a player holds at a time
# recommended values: min = 3, max = 6
quest-amount: 3

# times a player is allowed to skip a quest. (resets every day)
skips-per-day: 1

# broadcasts a message to everyone if a player completes a quest
broadcast-on-quest-complete: true

# plays a sound when a quest has been completed (only for the player)
sound-on-quest-complete: true

# disable the inbuilt scoreboard (/quests scoreboard)
# should only be set to true if the scoreboard does not work correctly because of another plugin using it.
# quests can always be displayed on custom scoreboards using the PlaceholderAPI.
disable-scoreboard: false

# show the scoreboard per default for new players
show-scoreboard-per-default: true

# set the locale for the plugin.
# contact me if you would like to have your language supported. you might need to help with translations.
# available locales:
# en: English, de: German, es: Spanish, fr: French, ru: Russian
locale: en

# whether new updates should be announced to admins and in the console.
# updating to the newest version is always recommended unless the new version is not compatible with your server.
check-for-updates: true

# save interval for player data in minutes
# the saving process can cause lag on large servers. Increase this parameter to make savings less frequent.
# recommended values: min = 10
save-interval: 10

# edit the following list to prevent quest progress in worlds with the given names.
# watch out to not mess up the list's format.
banned-worlds:
  - world_creative
  - world_without_quest_progress

# an alternative character the plugin should use to display stars earned by quests
# replaces the default character. should be a valid unicode character.
# uncomment the following line to enable alternative character.
# star-character: "*"

# only relevant if you use the EssentialsX Discord Plugin!
# whether BasicQuests should connect to EssentialsX Discord when available.
# this will send a message with the type "quest-completed" to your discord server when a player completes a quest.
use-essentialsx-discord: true


# QUEST GENERATION

# factor for the value of rewards
# recommended values: min = 0.5, max = 3.0
reward-factor: 1.0

# factor for the quantities in a quest - e.g., the numbers of zombies to kill
# recommended values: min = 0.5, max = 3.0
quantity-factor: 1.0

# Increase the quantities in quests according to a players play time.
increase-quantity-by-playtime: true

# factor when a player joins the game
start-factor: 0.4

# factor when a player reaches <max-amount-hours> hours of playtime
max-factor: 3.0

# hours of play time at which a player receives quests with max quantities
max-amount-hours: 100

# chance of duplicate quests [0.0 - 1.0]
# 0.0: no duplicate quests will appear (not recommended when quest-amount is above 4)
# 1.0: players active quests have no influence on the generation of new quests
duplicate-quest-chance: 0.3



# REWARDS
# choose what type of reward you would like to be generated for quests.
# if multiple types are set to true, new quests will have a reward type chosen randomly.
# the weight of each reward type determines the likelihood of it being chosen compared to the weights of other enabled reward types.

# enable items as rewards
item-rewards: true
item-rewards-weight: 1

# enable xp as a reward
xp-rewards: false
xp-rewards-weight: 1

# enable money as a reward (requires an economy plugin to be hooked up via Vault)
money-rewards: false
money-rewards-weight: 1



# ECONOMY

# factor for money rewards
# adjusts this to the value of money on your server.
money-factor: 1.0
